# Generated by Django 6.0 on 2026-01-05 14:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("parents", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "class_level",
                    models.CharField(
                        choices=[
                            ("pre_nursery", "Pre-Nursery"),
                            ("nursery_1", "Nursery 1"),
                            ("nursery_2", "Nursery 2"),
                            ("kg_1", "Kindergarten 1"),
                            ("kg_2", "Kindergarten 2"),
                            ("primary_1", "Primary 1"),
                            ("primary_2", "Primary 2"),
                            ("primary_3", "Primary 3"),
                            ("primary_4", "Primary 4"),
                            ("primary_5", "Primary 5"),
                            ("primary_6", "Primary 6"),
                            ("jss_1", "JSS 1 (JS 1)"),
                            ("jss_2", "JSS 2 (JS 2)"),
                            ("jss_3", "JSS 3 (JS 3)"),
                            ("sss_1", "SSS 1 (SS 1)"),
                            ("sss_2", "SSS 2 (SS 2)"),
                            ("sss_3", "SSS 3 (SS 3)"),
                        ],
                        default="primary_1",
                        help_text="Current class/grade level",
                        max_length=20,
                    ),
                ),
                (
                    "stream",
                    models.CharField(
                        choices=[
                            ("science", "Science"),
                            ("commercial", "Commercial"),
                            ("art", "Arts/Humanities"),
                            ("general", "General (No stream yet)"),
                            ("technical", "Technical"),
                            ("none", "Not Applicable (Primary School)"),
                        ],
                        default="none",
                        help_text="Secondary school stream (Science/Commercial/Arts)",
                        max_length=20,
                    ),
                ),
                (
                    "admission_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="Date student was admitted",
                    ),
                ),
                (
                    "admission_number",
                    models.CharField(
                        blank=True,
                        help_text="School admission number (e.g., ADM/2024/001)",
                        max_length=20,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "student_id",
                    models.CharField(
                        blank=True,
                        help_text="School-specific student ID",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "house",
                    models.CharField(
                        choices=[
                            ("red", "Red House"),
                            ("blue", "Blue House"),
                            ("green", "Green House"),
                            ("yellow", "Yellow House"),
                            ("purple", "Purple House"),
                            ("orange", "Orange House"),
                            ("none", "No House Assigned"),
                        ],
                        default="none",
                        help_text="House/Group assignment",
                        max_length=20,
                    ),
                ),
                (
                    "previous_class",
                    models.CharField(
                        blank=True, help_text="Previous class attended", max_length=50
                    ),
                ),
                (
                    "previous_school",
                    models.CharField(
                        blank=True, help_text="Name of previous school", max_length=200
                    ),
                ),
                (
                    "transfer_certificate_no",
                    models.CharField(
                        blank=True,
                        help_text="Transfer certificate number",
                        max_length=50,
                    ),
                ),
                (
                    "is_prefect",
                    models.BooleanField(
                        default=False, help_text="Is this student a prefect?"
                    ),
                ),
                (
                    "prefect_role",
                    models.CharField(
                        blank=True, help_text="Prefect role/position", max_length=100
                    ),
                ),
                (
                    "student_category",
                    models.CharField(
                        choices=[
                            ("day", "Day Student"),
                            ("boarding", "Boarding Student"),
                            ("special_needs", "Special Needs Student"),
                            ("scholarship", "Scholarship Student"),
                            ("repeat", "Repeating Student"),
                            ("new", "New Student"),
                        ],
                        default="day",
                        help_text="Student category/type",
                        max_length=20,
                    ),
                ),
                (
                    "emergency_contact_name",
                    models.CharField(
                        blank=True, help_text="Emergency contact person", max_length=100
                    ),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(
                        blank=True, help_text="Emergency contact phone", max_length=15
                    ),
                ),
                (
                    "emergency_contact_relationship",
                    models.CharField(
                        blank=True, help_text="Relationship to student", max_length=50
                    ),
                ),
                (
                    "fee_status",
                    models.CharField(
                        choices=[
                            ("paid_full", "Paid in Full"),
                            ("paid_partial", "Partially Paid"),
                            ("not_paid", "Not Paid"),
                            ("scholarship", "On Scholarship"),
                            ("exempted", "Fee Exempted"),
                        ],
                        default="not_paid",
                        help_text="Current fee payment status",
                        max_length=20,
                    ),
                ),
                (
                    "total_fee_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Total fee amount for the term",
                        max_digits=10,
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Amount paid so far",
                        max_digits=10,
                    ),
                ),
                (
                    "balance_due",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Remaining balance to pay",
                        max_digits=10,
                    ),
                ),
                (
                    "fee_payment_evidence",
                    models.ImageField(
                        blank=True,
                        help_text="Upload payment receipt/evidence",
                        null=True,
                        upload_to="fee_evidence/",
                    ),
                ),
                (
                    "last_payment_date",
                    models.DateField(
                        blank=True, help_text="Date of last fee payment", null=True
                    ),
                ),
                (
                    "average_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Current average score",
                        max_digits=5,
                    ),
                ),
                (
                    "overall_grade",
                    models.CharField(
                        blank=True,
                        help_text="Overall grade (A, B, C, etc.)",
                        max_length=5,
                    ),
                ),
                (
                    "position_in_class",
                    models.PositiveIntegerField(
                        default=0, help_text="Position in class (rank)"
                    ),
                ),
                (
                    "blood_group",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "genotype",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("AA", "AA"),
                            ("AS", "AS"),
                            ("SS", "SS"),
                            ("AC", "AC"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "medical_conditions",
                    models.TextField(
                        blank=True, help_text="Any known medical conditions"
                    ),
                ),
                ("allergies", models.TextField(blank=True, help_text="Any allergies")),
                (
                    "transportation_mode",
                    models.CharField(
                        choices=[
                            ("school_bus", "School Bus"),
                            ("parent_drop", "Parent Drop-off"),
                            ("public_transport", "Public Transport"),
                            ("walk", "Walks to School"),
                            ("other", "Other"),
                        ],
                        default="parent_drop",
                        help_text="Mode of transportation to school",
                        max_length=20,
                    ),
                ),
                (
                    "bus_route",
                    models.CharField(
                        blank=True,
                        help_text="Bus route (if using school bus)",
                        max_length=100,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Is student currently active/enrolled?"
                    ),
                ),
                (
                    "is_graduated",
                    models.BooleanField(
                        default=False, help_text="Has student graduated?"
                    ),
                ),
                (
                    "graduation_date",
                    models.DateField(
                        blank=True, help_text="Date of graduation", null=True
                    ),
                ),
                (
                    "days_present",
                    models.PositiveIntegerField(
                        default=0, help_text="Total days present"
                    ),
                ),
                (
                    "days_absent",
                    models.PositiveIntegerField(
                        default=0, help_text="Total days absent"
                    ),
                ),
                (
                    "days_late",
                    models.PositiveIntegerField(default=0, help_text="Total days late"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "father",
                    models.ForeignKey(
                        blank=True,
                        help_text="Father/Guardian (Male)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="father_of_students",
                        to="parents.parent",
                    ),
                ),
                (
                    "mother",
                    models.ForeignKey(
                        blank=True,
                        help_text="Mother/Guardian (Female)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mother_of_students",
                        to="parents.parent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Student",
                "verbose_name_plural": "Students",
                "ordering": ["class_level", "user__first_name"],
            },
        ),
    ]
