# Generated by Django 4.2.11 on 2026-01-07 21:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("academic", "0002_initial"),
        ("parents", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentenrollment",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who approved the enrollment",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_enrollments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="studentenrollment",
            name="class_obj",
            field=models.ForeignKey(
                help_text="Class",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="academic.class",
            ),
        ),
        migrations.AddField(
            model_name="studentenrollment",
            name="enrolled_by",
            field=models.ForeignKey(
                help_text="User who enrolled the student",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="enrolled_students",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="studentenrollment",
            name="session",
            field=models.ForeignKey(
                help_text="Academic session",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="academic.academicsession",
            ),
        ),
        migrations.AddField(
            model_name="studentenrollment",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="students.student",
            ),
        ),
        migrations.AddField(
            model_name="studentenrollment",
            name="term",
            field=models.ForeignKey(
                help_text="Academic term",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="academic.academicterm",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="class_level",
            field=models.ForeignKey(
                blank=True,
                help_text="Current class/grade level",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="academic.classlevel",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="father",
            field=models.ForeignKey(
                blank=True,
                help_text="Father/Guardian (Male)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="father_of_students",
                to="parents.parent",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="mother",
            field=models.ForeignKey(
                blank=True,
                help_text="Mother/Guardian (Female)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mother_of_students",
                to="parents.parent",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="user",
            field=models.OneToOneField(
                help_text="Linked user account",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="studentenrollment",
            index=models.Index(fields=["status"], name="students_st_status_2a6b10_idx"),
        ),
        migrations.AddIndex(
            model_name="studentenrollment",
            index=models.Index(
                fields=["enrollment_date"], name="students_st_enrollm_255f97_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentenrollment",
            index=models.Index(
                fields=["student", "class_obj"], name="students_st_student_0430c7_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="studentenrollment",
            unique_together={("student", "session", "term", "class_obj")},
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["admission_number"], name="students_st_admissi_321db4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["class_level"], name="students_st_class_l_b62d5c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(fields=["stream"], name="students_st_stream_36d60e_idx"),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["fee_status"], name="students_st_fee_sta_152b5b_idx"
            ),
        ),
    ]
