# Generated by Django 4.2.11 on 2026-01-07 21:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academic", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "staff_id",
                    models.CharField(
                        blank=True,
                        help_text="Unique staff identification number",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "employment_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="Date staff was employed",
                    ),
                ),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("full_time", "Full-Time"),
                            ("part_time", "Part-Time"),
                            ("contract", "Contract"),
                            ("volunteer", "Volunteer"),
                            ("trainee", "Trainee/Intern"),
                        ],
                        default="full_time",
                        help_text="Type of employment",
                        max_length=20,
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("administration", "Administration"),
                            ("academic", "Academic"),
                            ("finance", "Finance/Bursary"),
                            ("library", "Library"),
                            ("laboratory", "Laboratory"),
                            ("ict", "ICT/Computer"),
                            ("security", "Security"),
                            ("maintenance", "Maintenance"),
                            ("transport", "Transport"),
                            ("health", "Health Clinic"),
                            ("counseling", "Guidance & Counseling"),
                            ("sports", "Sports & Games"),
                            ("none", "Not Applicable"),
                        ],
                        default="none",
                        help_text="Department/Unit assignment",
                        max_length=50,
                    ),
                ),
                (
                    "highest_qualification",
                    models.CharField(
                        blank=True,
                        help_text="Highest educational qualification (e.g., B.Sc, M.Ed, PhD)",
                        max_length=100,
                    ),
                ),
                (
                    "qualification_institution",
                    models.CharField(
                        blank=True,
                        help_text="Institution where qualification was obtained",
                        max_length=200,
                    ),
                ),
                (
                    "year_of_graduation",
                    models.IntegerField(
                        blank=True, help_text="Year of graduation", null=True
                    ),
                ),
                (
                    "professional_certifications",
                    models.TextField(
                        blank=True, help_text="Professional certifications (TRCN, etc.)"
                    ),
                ),
                (
                    "trcn_number",
                    models.CharField(
                        blank=True,
                        help_text="Teachers Registration Council of Nigeria Number",
                        max_length=50,
                    ),
                ),
                (
                    "specialization",
                    models.TextField(
                        blank=True, help_text="Areas of specialization/expertise"
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(
                        blank=True,
                        help_text="Bank name for salary payments",
                        max_length=100,
                    ),
                ),
                (
                    "account_name",
                    models.CharField(
                        blank=True,
                        help_text="Account name as registered with bank",
                        max_length=100,
                    ),
                ),
                (
                    "account_number",
                    models.CharField(
                        blank=True, help_text="Bank account number", max_length=20
                    ),
                ),
                (
                    "basic_salary",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Basic monthly salary",
                        max_digits=10,
                    ),
                ),
                (
                    "salary_scale",
                    models.CharField(
                        blank=True, help_text="Salary scale/grade level", max_length=50
                    ),
                ),
                (
                    "annual_leave_days",
                    models.IntegerField(
                        default=21, help_text="Annual leave entitlement in days"
                    ),
                ),
                (
                    "leave_days_taken",
                    models.IntegerField(
                        default=0, help_text="Leave days already taken"
                    ),
                ),
                (
                    "leave_days_remaining",
                    models.IntegerField(default=21, help_text="Remaining leave days"),
                ),
                (
                    "next_of_kin_name",
                    models.CharField(
                        blank=True, help_text="Next of kin full name", max_length=100
                    ),
                ),
                (
                    "next_of_kin_relationship",
                    models.CharField(
                        blank=True, help_text="Relationship to staff", max_length=50
                    ),
                ),
                (
                    "next_of_kin_phone",
                    models.CharField(
                        blank=True, help_text="Next of kin phone number", max_length=15
                    ),
                ),
                (
                    "next_of_kin_address",
                    models.TextField(blank=True, help_text="Next of kin address"),
                ),
                (
                    "blood_group",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "genotype",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("AA", "AA"),
                            ("AS", "AS"),
                            ("SS", "SS"),
                            ("AC", "AC"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "medical_conditions",
                    models.TextField(
                        blank=True, help_text="Any known medical conditions"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Is staff currently active/employed?"
                    ),
                ),
                (
                    "is_retired",
                    models.BooleanField(default=False, help_text="Has staff retired?"),
                ),
                (
                    "retirement_date",
                    models.DateField(
                        blank=True, help_text="Date of retirement", null=True
                    ),
                ),
                (
                    "is_on_leave",
                    models.BooleanField(
                        default=False, help_text="Is staff currently on leave?"
                    ),
                ),
                (
                    "leave_start_date",
                    models.DateField(
                        blank=True, help_text="Leave start date", null=True
                    ),
                ),
                (
                    "leave_end_date",
                    models.DateField(blank=True, help_text="Leave end date", null=True),
                ),
                (
                    "performance_rating",
                    models.DecimalField(
                        decimal_places=1,
                        default=0.0,
                        help_text="Overall performance rating (0-5)",
                        max_digits=3,
                    ),
                ),
                (
                    "last_appraisal_date",
                    models.DateField(
                        blank=True,
                        help_text="Date of last performance appraisal",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Staff",
                "verbose_name_plural": "Staff",
                "ordering": ["user__first_name"],
            },
        ),
        migrations.CreateModel(
            name="TeacherProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "teacher_type",
                    models.CharField(
                        choices=[
                            ("class_teacher", "Class Teacher"),
                            ("subject_teacher", "Subject Teacher"),
                            ("both", "Class & Subject Teacher"),
                            ("head_of_department", "Head of Department"),
                            ("vice_principal_academic", "Vice Principal (Academic)"),
                            ("principal", "Principal"),
                            ("head", "Head of School"),
                        ],
                        default="subject_teacher",
                        help_text="Type of teaching role",
                        max_length=30,
                    ),
                ),
                (
                    "stream_specialization",
                    models.CharField(
                        choices=[
                            ("science", "Science"),
                            ("commercial", "Commercial"),
                            ("arts", "Arts/Humanities"),
                            ("general", "General (All Streams)"),
                            ("none", "Not Applicable"),
                        ],
                        default="none",
                        help_text="Stream specialization for Senior Secondary",
                        max_length=20,
                    ),
                ),
                (
                    "max_periods_per_week",
                    models.IntegerField(
                        default=40, help_text="Maximum teaching periods per week"
                    ),
                ),
                (
                    "current_periods_per_week",
                    models.IntegerField(
                        default=0, help_text="Current teaching periods per week"
                    ),
                ),
                (
                    "years_of_experience",
                    models.IntegerField(
                        default=0, help_text="Total years of teaching experience"
                    ),
                ),
                (
                    "previous_schools",
                    models.TextField(
                        blank=True, help_text="Previous schools taught at"
                    ),
                ),
                (
                    "workshops_attended",
                    models.TextField(
                        blank=True,
                        help_text="Professional development workshops attended",
                    ),
                ),
                (
                    "training_certificates",
                    models.TextField(
                        blank=True, help_text="Training certificates obtained"
                    ),
                ),
                (
                    "has_teaching_materials",
                    models.BooleanField(
                        default=False, help_text="Has personal teaching materials"
                    ),
                ),
                (
                    "teaching_materials_description",
                    models.TextField(
                        blank=True,
                        help_text="Description of teaching materials available",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_classes",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Classes assigned as class teacher",
                        related_name="class_teachers",
                        to="academic.class",
                    ),
                ),
                (
                    "class_levels",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Class levels teacher can teach",
                        related_name="teachers",
                        to="academic.classlevel",
                    ),
                ),
                (
                    "staff",
                    models.OneToOneField(
                        help_text="Linked staff profile",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_profile",
                        to="staff.staff",
                    ),
                ),
                (
                    "subjects",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Subjects teacher can teach",
                        related_name="teachers",
                        to="academic.subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Teacher Profile",
                "verbose_name_plural": "Teacher Profiles",
                "ordering": ["staff__user__first_name"],
            },
        ),
        migrations.CreateModel(
            name="StaffPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "can_view_all_results",
                    models.BooleanField(
                        default=False, help_text="Can view all students' results"
                    ),
                ),
                (
                    "can_edit_results",
                    models.BooleanField(
                        default=False, help_text="Can edit examination results"
                    ),
                ),
                (
                    "can_approve_results",
                    models.BooleanField(
                        default=False, help_text="Can approve final results"
                    ),
                ),
                (
                    "can_generate_reports",
                    models.BooleanField(
                        default=False, help_text="Can generate academic reports"
                    ),
                ),
                (
                    "can_add_students",
                    models.BooleanField(
                        default=False, help_text="Can add new students"
                    ),
                ),
                (
                    "can_edit_students",
                    models.BooleanField(
                        default=False, help_text="Can edit student profiles"
                    ),
                ),
                (
                    "can_view_all_students",
                    models.BooleanField(
                        default=False, help_text="Can view all students"
                    ),
                ),
                (
                    "can_add_parents",
                    models.BooleanField(default=False, help_text="Can add new parents"),
                ),
                (
                    "can_edit_parents",
                    models.BooleanField(
                        default=False, help_text="Can edit parent profiles"
                    ),
                ),
                (
                    "can_add_staff",
                    models.BooleanField(default=False, help_text="Can add new staff"),
                ),
                (
                    "can_edit_staff",
                    models.BooleanField(
                        default=False, help_text="Can edit staff profiles"
                    ),
                ),
                (
                    "can_view_all_staff",
                    models.BooleanField(default=False, help_text="Can view all staff"),
                ),
                (
                    "can_view_finances",
                    models.BooleanField(
                        default=False, help_text="Can view financial records"
                    ),
                ),
                (
                    "can_edit_finances",
                    models.BooleanField(
                        default=False, help_text="Can edit financial records"
                    ),
                ),
                (
                    "can_generate_financial_reports",
                    models.BooleanField(
                        default=False, help_text="Can generate financial reports"
                    ),
                ),
                (
                    "can_manage_system_settings",
                    models.BooleanField(
                        default=False, help_text="Can manage system settings"
                    ),
                ),
                (
                    "can_view_audit_logs",
                    models.BooleanField(
                        default=False, help_text="Can view system audit logs"
                    ),
                ),
                (
                    "can_manage_backups",
                    models.BooleanField(
                        default=False, help_text="Can manage system backups"
                    ),
                ),
                (
                    "can_send_broadcast_messages",
                    models.BooleanField(
                        default=False, help_text="Can send broadcast messages"
                    ),
                ),
                (
                    "can_send_individual_messages",
                    models.BooleanField(
                        default=True, help_text="Can send individual messages"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "staff",
                    models.OneToOneField(
                        help_text="Staff member",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissions",
                        to="staff.staff",
                    ),
                ),
            ],
            options={
                "verbose_name": "Staff Permission",
                "verbose_name_plural": "Staff Permissions",
            },
        ),
        migrations.CreateModel(
            name="StaffAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now, help_text="Attendance date"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("absent", "Absent"),
                            ("late", "Late"),
                            ("half_day", "Half Day"),
                            ("leave", "On Leave"),
                            ("off_duty", "Off Duty"),
                            ("sick", "Sick Leave"),
                            ("emergency", "Emergency Leave"),
                            ("training", "Training/Workshop"),
                            ("other", "Other"),
                        ],
                        default="present",
                        help_text="Attendance status",
                        max_length=20,
                    ),
                ),
                (
                    "check_in_time",
                    models.TimeField(blank=True, help_text="Check-in time", null=True),
                ),
                (
                    "check_out_time",
                    models.TimeField(blank=True, help_text="Check-out time", null=True),
                ),
                (
                    "hours_worked",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Total hours worked",
                        max_digits=4,
                    ),
                ),
                (
                    "leave_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("annual", "Annual Leave"),
                            ("sick", "Sick Leave"),
                            ("maternity", "Maternity Leave"),
                            ("paternity", "Paternity Leave"),
                            ("casual", "Casual Leave"),
                            ("compassionate", "Compassionate Leave"),
                            ("study", "Study Leave"),
                            ("unpaid", "Unpaid Leave"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "leave_days_deducted",
                    models.IntegerField(
                        default=0, help_text="Number of leave days deducted"
                    ),
                ),
                (
                    "remarks",
                    models.TextField(
                        blank=True, help_text="Additional remarks or notes"
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Has attendance been verified by supervisor?",
                    ),
                ),
                (
                    "verification_date",
                    models.DateTimeField(
                        blank=True, help_text="Date and time of verification", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Staff who recorded this attendance",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_attendances",
                        to="staff.staff",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        help_text="Staff member",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="staff.staff",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Supervisor who verified attendance",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_attendances",
                        to="staff.staff",
                    ),
                ),
            ],
            options={
                "verbose_name": "Staff Attendance",
                "verbose_name_plural": "Staff Attendances",
                "ordering": ["-date", "staff__user__first_name"],
            },
        ),
    ]
