# Generated by Django 4.2.11 on 2026-01-07 21:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="user",
            field=models.OneToOneField(
                help_text="Linked user account",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="staff_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="staffattendance",
            index=models.Index(
                fields=["staff", "date"], name="staff_staff_staff_i_9c87ac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staffattendance",
            index=models.Index(fields=["status"], name="staff_staff_status_e16c6c_idx"),
        ),
        migrations.AddIndex(
            model_name="staffattendance",
            index=models.Index(fields=["date"], name="staff_staff_date_5bf703_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="staffattendance",
            unique_together={("staff", "date")},
        ),
        migrations.AddIndex(
            model_name="staff",
            index=models.Index(
                fields=["staff_id"], name="staff_staff_staff_i_1228db_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staff",
            index=models.Index(
                fields=["employment_type"], name="staff_staff_employm_56a539_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staff",
            index=models.Index(
                fields=["department"], name="staff_staff_departm_eea1cc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staff",
            index=models.Index(
                fields=["is_active"], name="staff_staff_is_acti_0db61a_idx"
            ),
        ),
    ]
