# Generated by Django 4.2.11 on 2026-01-07 21:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "registration_number",
                    models.CharField(
                        help_text="Auto-generated: first 4 letters of first name + 4 digits",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("head", "Head of School/Proprietor"),
                            ("principal", "Principal"),
                            ("vice_principal", "Vice Principal"),
                            ("teacher", "Teacher"),
                            ("form_teacher", "Form Teacher"),
                            ("subject_teacher", "Subject Teacher"),
                            ("student", "Student"),
                            ("parent", "Parent/Guardian"),
                            ("accountant", "Accountant/Bursar"),
                            ("secretary", "Secretary"),
                            ("librarian", "Librarian"),
                            ("laboratory", "Laboratory Technician"),
                            ("security", "Security Personnel"),
                            ("cleaner", "Cleaner"),
                        ],
                        default="student",
                        max_length=20,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("male", "Male"), ("female", "Female")],
                        max_length=10,
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("phone_number", models.CharField(blank=True, max_length=15)),
                ("alternative_phone", models.CharField(blank=True, max_length=15)),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="profile_pictures/"
                    ),
                ),
                ("address", models.TextField(blank=True)),
                ("city", models.CharField(blank=True, max_length=100)),
                (
                    "state_of_origin",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("abia", "Abia"),
                            ("adamawa", "Adamawa"),
                            ("akwa_ibom", "Akwa Ibom"),
                            ("anambra", "Anambra"),
                            ("bauchi", "Bauchi"),
                            ("bayelsa", "Bayelsa"),
                            ("benue", "Benue"),
                            ("borno", "Borno"),
                            ("cross_river", "Cross River"),
                            ("delta", "Delta"),
                            ("ebonyi", "Ebonyi"),
                            ("edo", "Edo"),
                            ("ekiti", "Ekiti"),
                            ("enugu", "Enugu"),
                            ("gombe", "Gombe"),
                            ("imo", "Imo"),
                            ("jigawa", "Jigawa"),
                            ("kaduna", "Kaduna"),
                            ("kano", "Kano"),
                            ("katsina", "Katsina"),
                            ("kebbi", "Kebbi"),
                            ("kogi", "Kogi"),
                            ("kwara", "Kwara"),
                            ("lagos", "Lagos"),
                            ("nasarawa", "Nasarawa"),
                            ("niger", "Niger"),
                            ("ogun", "Ogun"),
                            ("ondo", "Ondo"),
                            ("osun", "Osun"),
                            ("oyo", "Oyo"),
                            ("plateau", "Plateau"),
                            ("rivers", "Rivers"),
                            ("sokoto", "Sokoto"),
                            ("taraba", "Taraba"),
                            ("yobe", "Yobe"),
                            ("zamfara", "Zamfara"),
                            ("fct", "Federal Capital Territory"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "lga",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Local Government Area"
                    ),
                ),
                ("nationality", models.CharField(default="Nigerian", max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("last_login_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("login_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["registration_number"],
                        name="users_user_registr_54ab4a_idx",
                    ),
                    models.Index(fields=["email"], name="users_user_email_6f2530_idx"),
                    models.Index(fields=["role"], name="users_user_role_36d76d_idx"),
                ],
            },
        ),
    ]
