# Generated by Django 4.2.11 on 2026-01-07 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AcademicSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Academic session name (e.g., 2024/2025 Academic Session)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("start_date", models.DateField(help_text="Session start date")),
                ("end_date", models.DateField(help_text="Session end date")),
                (
                    "is_current",
                    models.BooleanField(
                        default=False, help_text="Is this the current academic session?"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("upcoming", "Upcoming"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("archived", "Archived"),
                        ],
                        default="upcoming",
                        help_text="Session status",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Additional notes about the session"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Academic Session",
                "verbose_name_plural": "Academic Sessions",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="AcademicTerm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "term",
                    models.CharField(
                        choices=[
                            ("first", "First Term"),
                            ("second", "Second Term"),
                            ("third", "Third Term"),
                        ],
                        help_text="Term name",
                        max_length=20,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Term display name (e.g., First Term 2024/2025)",
                        max_length=100,
                    ),
                ),
                ("start_date", models.DateField(help_text="Term start date")),
                ("end_date", models.DateField(help_text="Term end date")),
                (
                    "is_current",
                    models.BooleanField(
                        default=False, help_text="Is this the current term?"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("upcoming", "Upcoming"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                        ],
                        default="upcoming",
                        help_text="Term status",
                        max_length=20,
                    ),
                ),
                (
                    "total_school_days",
                    models.IntegerField(
                        default=0, help_text="Total number of school days in term"
                    ),
                ),
                (
                    "total_teaching_weeks",
                    models.IntegerField(
                        default=0, help_text="Total number of teaching weeks"
                    ),
                ),
                (
                    "holiday_weeks",
                    models.IntegerField(default=0, help_text="Number of holiday weeks"),
                ),
                (
                    "examination_weeks",
                    models.IntegerField(
                        default=0, help_text="Number of examination weeks"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Term activities and important dates"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Academic Term",
                "verbose_name_plural": "Academic Terms",
                "ordering": ["session__start_date", "term"],
            },
        ),
        migrations.CreateModel(
            name="Class",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Class name (e.g., Primary 1A, JSS 1B)",
                        max_length=100,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Class code (e.g., P1A-2024-1)", max_length=20
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="URL-friendly class identifier",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "max_capacity",
                    models.IntegerField(
                        default=40, help_text="Maximum number of students"
                    ),
                ),
                (
                    "current_enrollment",
                    models.IntegerField(
                        default=0, help_text="Current number of enrolled students"
                    ),
                ),
                (
                    "room_number",
                    models.CharField(
                        blank=True, help_text="Classroom number/building", max_length=20
                    ),
                ),
                (
                    "building",
                    models.CharField(
                        blank=True, help_text="Building name", max_length=100
                    ),
                ),
                (
                    "floor",
                    models.CharField(
                        blank=True, help_text="Floor/level", max_length=20
                    ),
                ),
                (
                    "stream",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("science", "Science"),
                            ("commercial", "Commercial"),
                            ("arts", "Arts/Humanities"),
                            ("general", "General"),
                            ("technical", "Technical"),
                        ],
                        help_text="Class stream (for Senior Secondary)",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("graduated", "Graduated"),
                            ("archived", "Archived"),
                        ],
                        default="active",
                        help_text="Class status",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Is this class currently active?"
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True, help_text="Class start date", null=True
                    ),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, help_text="Class end date", null=True),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Class description and notes"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Class",
                "verbose_name_plural": "Classes",
                "ordering": ["class_level__order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ClassLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("creche", "Creche (0-2 years)"),
                            ("playgroup", "Playgroup (2-3 years)"),
                            ("nursery_1", "Nursery 1 (3-4 years)"),
                            ("nursery_2", "Nursery 2 (4-5 years)"),
                            ("kg_1", "Kindergarten 1 (KG 1)"),
                            ("kg_2", "Kindergarten 2 (KG 2)"),
                            ("primary_1", "Primary 1 (Basic 1)"),
                            ("primary_2", "Primary 2 (Basic 2)"),
                            ("primary_3", "Primary 3 (Basic 3)"),
                            ("primary_4", "Primary 4 (Basic 4)"),
                            ("primary_5", "Primary 5 (Basic 5)"),
                            ("primary_6", "Primary 6 (Basic 6)"),
                            ("jss_1", "JSS 1 (Junior Secondary 1)"),
                            ("jss_2", "JSS 2 (Junior Secondary 2)"),
                            ("jss_3", "JSS 3 (Junior Secondary 3)"),
                            ("sss_1", "SSS 1 (Senior Secondary 1)"),
                            ("sss_2", "SSS 2 (Senior Secondary 2)"),
                            ("sss_3", "SSS 3 (Senior Secondary 3)"),
                        ],
                        help_text="Class level",
                        max_length=20,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Level display name (e.g., Primary 1)", max_length=100
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Level code (e.g., P1, JSS1, SSS1)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Sorting order within program"
                    ),
                ),
                (
                    "min_age",
                    models.IntegerField(
                        default=0, help_text="Minimum age for this level"
                    ),
                ),
                (
                    "max_age",
                    models.IntegerField(
                        default=0, help_text="Maximum age for this level"
                    ),
                ),
                (
                    "is_promotion_level",
                    models.BooleanField(
                        default=False,
                        help_text="Is this a promotion/examination level?",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Is this level currently active?"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Level description and objectives"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Class Level",
                "verbose_name_plural": "Class Levels",
                "ordering": ["program__program_type", "order"],
            },
        ),
        migrations.CreateModel(
            name="ClassSubject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True, help_text="Teaching start date", null=True
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, help_text="Teaching end date", null=True
                    ),
                ),
                (
                    "periods_per_week",
                    models.IntegerField(default=0, help_text="Actual periods per week"),
                ),
                (
                    "preferred_days",
                    models.CharField(
                        blank=True,
                        help_text="Preferred teaching days (comma-separated)",
                        max_length=100,
                    ),
                ),
                (
                    "preferred_times",
                    models.CharField(
                        blank=True, help_text="Preferred teaching times", max_length=100
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Is this assignment currently active?"
                    ),
                ),
                (
                    "is_compulsory",
                    models.BooleanField(
                        default=False,
                        help_text="Is this subject compulsory for this class?",
                    ),
                ),
                (
                    "ca_required",
                    models.BooleanField(
                        default=True, help_text="Continuous assessment required?"
                    ),
                ),
                (
                    "exam_required",
                    models.BooleanField(
                        default=True, help_text="Examination required?"
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="Additional notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Class Subject Assignment",
                "verbose_name_plural": "Class Subject Assignments",
                "ordering": ["class_obj", "subject"],
            },
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Program name (e.g., Primary Education)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "program_type",
                    models.CharField(
                        choices=[
                            ("pre_school", "Pre-School (Creche, Nursery, KG)"),
                            ("primary", "Primary School (Basic 1-6)"),
                            ("junior_secondary", "Junior Secondary School (JSS 1-3)"),
                            ("senior_secondary", "Senior Secondary School (SSS 1-3)"),
                            ("special_education", "Special Education"),
                            ("adult_education", "Adult Education"),
                            ("vocational", "Vocational Training"),
                        ],
                        help_text="Type of academic program",
                        max_length=30,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Program code (e.g., PRI, JSS, SSS)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Program description and objectives"
                    ),
                ),
                (
                    "duration_years",
                    models.IntegerField(
                        default=0, help_text="Program duration in years"
                    ),
                ),
                (
                    "curriculum",
                    models.CharField(
                        blank=True,
                        help_text="Curriculum followed (e.g., Nigerian, British, American)",
                        max_length=100,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Is this program currently active?"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Academic Program",
                "verbose_name_plural": "Academic Programs",
                "ordering": ["program_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Subject name (e.g., Mathematics)",
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Subject code (e.g., MAT, ENG, PHY)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        blank=True,
                        help_text="Short name or abbreviation",
                        max_length=50,
                    ),
                ),
                (
                    "subject_type",
                    models.CharField(
                        choices=[
                            ("core", "Core Subject"),
                            ("elective", "Elective Subject"),
                            ("vocational", "Vocational Subject"),
                            ("extra_curricular", "Extra-Curricular"),
                            ("religious", "Religious Studies"),
                            ("language", "Language"),
                            ("science", "Science"),
                            ("arts", "Arts/Humanities"),
                            ("commercial", "Commercial/Business"),
                            ("technical", "Technical"),
                            ("general", "General Studies"),
                        ],
                        default="core",
                        help_text="Type of subject",
                        max_length=30,
                    ),
                ),
                (
                    "stream",
                    models.CharField(
                        choices=[
                            ("science", "Science Stream"),
                            ("commercial", "Commercial Stream"),
                            ("arts", "Arts/Humanities Stream"),
                            ("general", "General (All Streams)"),
                            ("technical", "Technical Stream"),
                        ],
                        default="general",
                        help_text="Stream specialization (for Senior Secondary)",
                        max_length=20,
                    ),
                ),
                (
                    "curriculum",
                    models.CharField(
                        blank=True,
                        help_text="Curriculum specification (e.g., WAEC, NECO, BECE)",
                        max_length=100,
                    ),
                ),
                (
                    "syllabus",
                    models.FileField(
                        blank=True,
                        help_text="Subject syllabus document",
                        null=True,
                        upload_to="syllabus/",
                    ),
                ),
                (
                    "periods_per_week",
                    models.IntegerField(
                        default=5, help_text="Number of teaching periods per week"
                    ),
                ),
                (
                    "minutes_per_period",
                    models.IntegerField(
                        default=40, help_text="Duration of each period in minutes"
                    ),
                ),
                (
                    "total_teaching_hours",
                    models.IntegerField(
                        default=0, help_text="Total teaching hours per term"
                    ),
                ),
                (
                    "has_continuous_assessment",
                    models.BooleanField(
                        default=True,
                        help_text="Does this subject have continuous assessment?",
                    ),
                ),
                (
                    "ca_weight",
                    models.IntegerField(
                        default=30, help_text="Continuous assessment weight (%)"
                    ),
                ),
                (
                    "exam_weight",
                    models.IntegerField(default=70, help_text="Examination weight (%)"),
                ),
                (
                    "is_compulsory",
                    models.BooleanField(
                        default=False, help_text="Is this a compulsory subject?"
                    ),
                ),
                (
                    "is_examinable",
                    models.BooleanField(
                        default=True, help_text="Is this subject examinable?"
                    ),
                ),
                (
                    "is_practical",
                    models.BooleanField(
                        default=False,
                        help_text="Does this subject have practical components?",
                    ),
                ),
                (
                    "subject_group",
                    models.CharField(
                        blank=True,
                        help_text="Subject group/combination",
                        max_length=100,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Is this subject currently active?"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Subject description and objectives"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Subject",
                "verbose_name_plural": "Subjects",
                "ordering": ["code", "name"],
            },
        ),
        migrations.CreateModel(
            name="Timetable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Timetable name (e.g., Primary School Timetable Term 1 2024)",
                        max_length=200,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Timetable code", max_length=50, unique=True
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("school", "Whole School"),
                            ("program", "Program"),
                            ("class_level", "Class Level"),
                            ("class", "Class"),
                            ("teacher", "Teacher"),
                        ],
                        default="class",
                        help_text="Timetable scope",
                        max_length=20,
                    ),
                ),
                (
                    "days",
                    models.CharField(
                        default="monday,tuesday,wednesday,thursday,friday",
                        help_text="School days (comma-separated)",
                        max_length=200,
                    ),
                ),
                (
                    "periods_per_day",
                    models.IntegerField(
                        default=8, help_text="Number of periods per day"
                    ),
                ),
                (
                    "period_duration",
                    models.IntegerField(
                        default=40, help_text="Duration of each period in minutes"
                    ),
                ),
                (
                    "break_periods",
                    models.CharField(
                        default="4",
                        help_text="Period numbers for breaks (comma-separated)",
                        max_length=100,
                    ),
                ),
                (
                    "lunch_period",
                    models.IntegerField(default=5, help_text="Lunch period number"),
                ),
                (
                    "assembly_period",
                    models.IntegerField(default=1, help_text="Assembly period number"),
                ),
                (
                    "start_time",
                    models.TimeField(default="08:00", help_text="School start time"),
                ),
                (
                    "end_time",
                    models.TimeField(default="15:00", help_text="School end time"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("active", "Active"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        help_text="Timetable status",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False, help_text="Is this the active timetable?"
                    ),
                ),
                (
                    "is_locked",
                    models.BooleanField(
                        default=False, help_text="Is timetable locked from edits?"
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        default="1.0", help_text="Timetable version", max_length=20
                    ),
                ),
                (
                    "approved_date",
                    models.DateTimeField(
                        blank=True, help_text="Approval date", null=True
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Timetable description and notes"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Timetable",
                "verbose_name_plural": "Timetables",
                "ordering": ["-session__start_date", "-term__term", "name"],
            },
        ),
        migrations.CreateModel(
            name="TimetableEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("monday", "Monday"),
                            ("tuesday", "Tuesday"),
                            ("wednesday", "Wednesday"),
                            ("thursday", "Thursday"),
                            ("friday", "Friday"),
                            ("saturday", "Saturday"),
                        ],
                        help_text="Day of the week",
                        max_length=20,
                    ),
                ),
                (
                    "period_number",
                    models.IntegerField(help_text="Period number (1-10)"),
                ),
                (
                    "room",
                    models.CharField(blank=True, help_text="Room/venue", max_length=50),
                ),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("subject", "Subject Teaching"),
                            ("assembly", "Assembly"),
                            ("break", "Break Time"),
                            ("lunch", "Lunch Break"),
                            ("sports", "Sports/Games"),
                            ("club", "Club Activity"),
                            ("study", "Study Period"),
                            ("test", "Test/Examination"),
                            ("meeting", "Staff Meeting"),
                            ("other", "Other Activity"),
                        ],
                        default="subject",
                        help_text="Type of timetable entry",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Is this entry active?"
                    ),
                ),
                (
                    "is_locked",
                    models.BooleanField(
                        default=False, help_text="Is this entry locked from changes?"
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="Additional notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "class_obj",
                    models.ForeignKey(
                        blank=True,
                        help_text="Class for this period",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timetable_entries",
                        to="academic.class",
                    ),
                ),
            ],
            options={
                "verbose_name": "Timetable Entry",
                "verbose_name_plural": "Timetable Entries",
                "ordering": ["timetable", "day", "period_number"],
            },
        ),
    ]
