# Generated by Django 4.2.11 on 2026-01-07 21:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("academic", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="timetableentry",
            name="created_by",
            field=models.ForeignKey(
                help_text="User who created this entry",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_timetable_entries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="timetableentry",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                help_text="Subject for this period",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="timetable_entries",
                to="academic.subject",
            ),
        ),
        migrations.AddField(
            model_name="timetableentry",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                help_text="Teacher for this period",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="timetable_periods",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="timetableentry",
            name="timetable",
            field=models.ForeignKey(
                help_text="Parent timetable",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entries",
                to="academic.timetable",
            ),
        ),
        migrations.AddField(
            model_name="timetable",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who approved this timetable",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_timetables",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="timetable",
            name="class_level",
            field=models.ForeignKey(
                blank=True,
                help_text="Target class level (if scope is class_level)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="timetables",
                to="academic.classlevel",
            ),
        ),
        migrations.AddField(
            model_name="timetable",
            name="class_obj",
            field=models.ForeignKey(
                blank=True,
                help_text="Target class (if scope is class)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="timetables",
                to="academic.class",
            ),
        ),
        migrations.AddField(
            model_name="timetable",
            name="created_by",
            field=models.ForeignKey(
                help_text="User who created this timetable",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_timetables",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="timetable",
            name="parent_timetable",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent timetable for versioning",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="revisions",
                to="academic.timetable",
            ),
        ),
        migrations.AddField(
            model_name="timetable",
            name="program",
            field=models.ForeignKey(
                blank=True,
                help_text="Target program (if scope is program)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="timetables",
                to="academic.program",
            ),
        ),
        migrations.AddField(
            model_name="timetable",
            name="session",
            field=models.ForeignKey(
                help_text="Academic session",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="timetables",
                to="academic.academicsession",
            ),
        ),
        migrations.AddField(
            model_name="timetable",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                help_text="Target teacher (if scope is teacher)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="timetables",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="timetable",
            name="term",
            field=models.ForeignKey(
                help_text="Academic term",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="timetables",
                to="academic.academicterm",
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="class_levels",
            field=models.ManyToManyField(
                blank=True,
                help_text="Class levels where this subject is taught",
                related_name="subjects",
                to="academic.classlevel",
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="created_by",
            field=models.ForeignKey(
                help_text="User who created this subject",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_subjects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="programs",
            field=models.ManyToManyField(
                blank=True,
                help_text="Programs where this subject is taught",
                related_name="subjects",
                to="academic.program",
            ),
        ),
        migrations.AddField(
            model_name="classsubject",
            name="class_obj",
            field=models.ForeignKey(
                help_text="Class",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="class_subjects",
                to="academic.class",
            ),
        ),
        migrations.AddField(
            model_name="classsubject",
            name="co_teacher",
            field=models.ForeignKey(
                blank=True,
                help_text="Co-teacher",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="co_teaching_assignments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="classsubject",
            name="created_by",
            field=models.ForeignKey(
                help_text="User who created this assignment",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_class_subjects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="classsubject",
            name="subject",
            field=models.ForeignKey(
                help_text="Subject",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="class_assignments",
                to="academic.subject",
            ),
        ),
        migrations.AddField(
            model_name="classsubject",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                help_text="Assigned teacher",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="teaching_assignments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="classlevel",
            name="program",
            field=models.ForeignKey(
                help_text="Parent academic program",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="class_levels",
                to="academic.program",
            ),
        ),
        migrations.AddField(
            model_name="classlevel",
            name="required_previous_level",
            field=models.ForeignKey(
                blank=True,
                help_text="Previous level required for promotion",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="next_levels",
                to="academic.classlevel",
            ),
        ),
        migrations.AddField(
            model_name="class",
            name="assistant_class_teacher",
            field=models.ForeignKey(
                blank=True,
                help_text="Assistant class teacher",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assistant_classes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="class",
            name="class_level",
            field=models.ForeignKey(
                help_text="Class level",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classes",
                to="academic.classlevel",
            ),
        ),
        migrations.AddField(
            model_name="class",
            name="class_teacher",
            field=models.ForeignKey(
                blank=True,
                help_text="Primary class teacher",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="classes_taught",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="class",
            name="created_by",
            field=models.ForeignKey(
                help_text="User who created this class",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_classes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="class",
            name="session",
            field=models.ForeignKey(
                help_text="Academic session",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classes",
                to="academic.academicsession",
            ),
        ),
        migrations.AddField(
            model_name="class",
            name="subjects",
            field=models.ManyToManyField(
                blank=True,
                help_text="Subjects offered in this class",
                related_name="classes",
                through="academic.ClassSubject",
                to="academic.subject",
            ),
        ),
        migrations.AddField(
            model_name="class",
            name="term",
            field=models.ForeignKey(
                help_text="Academic term",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classes",
                to="academic.academicterm",
            ),
        ),
        migrations.AddField(
            model_name="academicterm",
            name="session",
            field=models.ForeignKey(
                help_text="Parent academic session",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="terms",
                to="academic.academicsession",
            ),
        ),
        migrations.AddIndex(
            model_name="academicsession",
            index=models.Index(
                fields=["is_current"], name="academic_ac_is_curr_605633_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="academicsession",
            index=models.Index(fields=["status"], name="academic_ac_status_6f24c2_idx"),
        ),
        migrations.AddIndex(
            model_name="timetableentry",
            index=models.Index(
                fields=["day", "period_number"], name="academic_ti_day_b151c5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="timetableentry",
            index=models.Index(
                fields=["teacher"], name="academic_ti_teacher_43ffb0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="timetableentry",
            index=models.Index(
                fields=["subject"], name="academic_ti_subject_c26c7f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="timetableentry",
            unique_together={("timetable", "day", "period_number", "class_obj")},
        ),
        migrations.AddIndex(
            model_name="timetable",
            index=models.Index(fields=["status"], name="academic_ti_status_54b52d_idx"),
        ),
        migrations.AddIndex(
            model_name="timetable",
            index=models.Index(
                fields=["is_active"], name="academic_ti_is_acti_626752_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="timetable",
            index=models.Index(fields=["scope"], name="academic_ti_scope_036dce_idx"),
        ),
        migrations.AddIndex(
            model_name="subject",
            index=models.Index(
                fields=["subject_type"], name="academic_su_subject_884882_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subject",
            index=models.Index(fields=["stream"], name="academic_su_stream_69ecce_idx"),
        ),
        migrations.AddIndex(
            model_name="subject",
            index=models.Index(
                fields=["is_active"], name="academic_su_is_acti_4e0783_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="classsubject",
            index=models.Index(
                fields=["is_active"], name="academic_cl_is_acti_25e6c2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="classsubject",
            index=models.Index(
                fields=["teacher"], name="academic_cl_teacher_577757_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="classsubject",
            unique_together={("class_obj", "subject")},
        ),
        migrations.AlterUniqueTogether(
            name="classlevel",
            unique_together={("program", "level")},
        ),
        migrations.AddIndex(
            model_name="class",
            index=models.Index(fields=["status"], name="academic_cl_status_ba7655_idx"),
        ),
        migrations.AddIndex(
            model_name="class",
            index=models.Index(
                fields=["is_active"], name="academic_cl_is_acti_d8f3bd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="class",
            index=models.Index(
                fields=["class_level"], name="academic_cl_class_l_600993_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="class",
            unique_together={("session", "term", "class_level", "name")},
        ),
        migrations.AddIndex(
            model_name="academicterm",
            index=models.Index(
                fields=["is_current"], name="academic_ac_is_curr_601a0d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="academicterm",
            index=models.Index(fields=["status"], name="academic_ac_status_970c02_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="academicterm",
            unique_together={("session", "term")},
        ),
    ]
